package render

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/greyquill/mcpsight/internal/analyze"
	"github.com/greyquill/mcpsight/internal/scan"
)

// Markdown writes a compact report suitable for pasting into a pull-request
// comment: a grade line, the headline numbers, and a findings table per server.
func Markdown(w io.Writer, reports []*scan.Report) error {
	for i, r := range reports {
		if i > 0 {
			fmt.Fprintln(w)
		}
		writeMarkdownReport(w, r)
	}
	return nil
}

func writeMarkdownReport(w io.Writer, r *scan.Report) {
	name := r.Server.Name
	if name == "" {
		name = r.Target.Name
	}
	fmt.Fprintf(w, "### mcpsight: `%s`, grade %s (%d/100%s)\n\n", name, r.Score.Grade, r.Score.Score, cappedNote(r))

	if len(r.ContextCost.Models) > 0 {
		m := r.ContextCost.Models[0]
		fmt.Fprintf(w, "**Context cost:** ~%s tokens (%s) · %s/req @ %s _(est.)_\n\n",
			commas(m.Tokens), toolCount(r.ContextCost.ToolCount), usd(m.USD), m.Model)
	}
	if caps := r.Capabilities.Classes; len(caps) > 0 {
		fmt.Fprintf(w, "**Capabilities:** %s\n\n", strings.Join(caps, ", "))
	}
	fmt.Fprintf(w, "**Drift:** %s\n\n", markdownDrift(r.BaselineState))

	if len(r.Findings) == 0 {
		fmt.Fprint(w, "No findings.\n\n")
	} else {
		sorted := append([]analyze.Finding(nil), r.Findings...)
		sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Severity.MoreSevereThan(sorted[j].Severity) })
		fmt.Fprintln(w, "| Severity | Finding | Tool |")
		fmt.Fprintln(w, "|---|---|---|")
		for _, f := range sorted {
			fmt.Fprintf(w, "| %s | %s <sub>`%s`</sub> | %s |\n",
				sevLabel(f.Severity), mdEscape(f.Title), f.RuleID, code(f.Tool))
		}
		fmt.Fprintln(w)
	}
	fmt.Fprintf(w, "<sub>Generated by [mcpsight](https://github.com/greyquill/mcpsight) · rubric v%d</sub>\n", r.RubricVersion)
}

// sevLabel bolds the two severities a reviewer must not miss.
func sevLabel(s analyze.Severity) string {
	if s == analyze.Critical || s == analyze.High {
		return "**" + string(s) + "**"
	}
	return string(s)
}

func markdownDrift(s scan.BaselineState) string {
	switch s {
	case scan.BaselineFirstScan:
		return "baseline recorded (first scan)"
	case scan.BaselineUnchanged:
		return "unchanged since baseline"
	case scan.BaselineDrifted:
		return "**drifted since baseline**"
	}
	return "unknown"
}

func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

// mdEscape escapes the pipe characters that would break a markdown table cell.
func mdEscape(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
